"""
Utils class with functions supporting fine-tuning.

Date: 2025-04-05
"""

import torch
import re
from enum import Enum
from typing import List, Union, Any, Dict, Callable
import asyncio

# Regular expression used to extract the response from the model's prediction.
ANSWER_REGEXP = r"<\|start_of_role\|>assistant<\|end_of_role\|>\s*(.*?)(?=\s*<\|end_of_text\|>|\Z)"

class Device(Enum):
    """
    Enumeration of supported computing devices.
    """
    CUDA = "cuda"
    MPS = "mps"
    CPU = "cpu"

def get_device():
    """
    Determines the most suitable device for model inference based on available hardware.

    Returns:
        str: A string indicating the available device for inference. The possible values are:
            - "cuda" if a CUDA-compatible GPU is available,
            - "mps" if an Apple device with MPS support is available,
            - "cpu" if no GPU accelerators are available.
    """
    if torch.cuda.is_available():
        return Device.CUDA
    elif torch.backends.mps.is_available():
        return Device.MPS
    else:
        return Device.CPU

def prepare_formatting_prompts_func(tokenizer: Any, add_generation_prompt: bool = False) -> Callable[[Union[str, Dict]], str]:
    """
    Creates a formatting function that prepares chat-style prompt messages
    for tokenization using a given tokenizer.

    Args:
        tokenizer (Any): A tokenizer with an `apply_chat_template` method
        add_generation_prompt (bool, optional): Whether to add a generation 
            prompt to the formatted message. Defaults to False.

    Returns:
        Callable: A function that formats a sample dictionary or prompt string 
        into a chat-style message using the provided tokenizer.
    """
    def formatting_prompts_func(sample: Union[str, Dict]) -> str:
        """
        Formats a sample into a chat-style prompt using a tokenizer.

        This function takes in a sample that can either be a dictionary with 
        'prompt' and optional 'response' keys or just a string. It returns 
        a formatted message for tokenization using the tokenizer's chat template.

        Args:
            sample (Union[str, Dict]): The input sample. It can either be a 
                string containing the prompt or a dictionary with the following
                keys:
                - 'prompt' (str): The user's prompt message.
                - 'response' (str, optional): The assistant's response.

        Returns:
            str: A string formatted using the tokenizer's chat template. 
                This string represents the prompt and, if available, the response
                from the assistant.
        """
        if isinstance(sample, str):
            prompt = sample
        else:
            prompt = sample['prompt']
        messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt},
        ]
        if 'response' in sample:
            messages.append({"role": "assistant", "content": sample['response']})
        
        chat = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=add_generation_prompt
        )

        return chat
    
    return formatting_prompts_func

async def inference(model: Any, tokenizer: Any, device: str, questions: Union[str, List[str]], max_new_tokens: int, batch_size: int = 1) -> List[str]:
    """
    Performs inference using a given model and tokenizer with batch processing.

    Args:
        model (Any): The generative model to use for inference.
        tokenizer (Any): The tokenizer used to process and convert text to tokens before inference.
        device (str): The device for model inference, such as 'cpu', 'cuda', or 'mps'.
        questions (Union[str, List[str]]): The question or the list of questions that will be put into the model for inference.
        max_new_tokens (int): The maximum number of new tokens the model should generate in its response.
        batch_size (int): The batch size for processing the questions in groups.

    Returns:
        List[str]: The list of responses generated by the model.
    """
    if isinstance(questions, str):
        questions = [questions]

    num_batches = (len(questions) + batch_size - 1) // batch_size
    predictions = []

    if batch_size > 1:
        print(f"Batch size: {batch_size}")

    for i in range(num_batches):
        if batch_size > 1:
            print(f"Processing batch {i+1} of {num_batches}")

        batch_questions = questions[i * batch_size:(i + 1) * batch_size]

        formatting_prompt_func = prepare_formatting_prompts_func(tokenizer, True)
        formatted_prompts = [
            formatting_prompt_func(chat)
            for chat in batch_questions
        ]

        inputs = tokenizer(formatted_prompts, return_tensors="pt", padding=True, truncation=True).to(device)
        
        outputs = model.generate(
            **inputs,
            do_sample=False,
            max_new_tokens=max_new_tokens,
            num_return_sequences=1
        )

        responses = [tokenizer.decode(output, skip_special_tokens=False) for output in outputs]

        batch_predictions = [(re.search(ANSWER_REGEXP, response, re.DOTALL) or [None, ""])[1].strip() for response in responses]

        predictions.extend(batch_predictions)

    return predictions